import './globals.css';
import Navbar from '@/components/navbar';
import Providers from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html className="min-h-screen" data-theme={'dark'} lang="en">
      <body className="min-h-screen">
        <Navbar />
        <main className="px-8 py-20 max-w-6xl mx-auto">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
